language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ylaguardia/docker-react-ste_grider -f Dockerfile.dev .

script:
  - docker run -e CI=true ylaguardia/docker-react-ste_grider npm run test
